### ISSUE TITLE
SonarCloud workflow does not allow to merge from forks

### ISSUE THREAD

**Issue by ilnarkhasanov** [yegor256/cam#250]
SonarCloud tries to run checks from the forked repository. Obviously, it fails since it needs `SONAR_TOKEN`.

<img width="476" alt="image" src="https://github.com/yegor256/cam/assets/37439026/f16f79e0-d701-4067-8a74-d897fcb4b434">

My suggestion is to check that SonarCloud runs only from the yegor256/cam.

For example:
```
jobs:
  sonarcloud:
    if: github.repository == 'yegor256/cam'
    runs-on: ubuntu-22.04
```
